eureka:
  client:
    healthcheck:
      enabled: true

owms:
  movement:
    putaway-resolution-enabled: true
    targets:
      - name: WAREHOUSE1
        search-location-group-names: RACK1,RACK2
        type: INBOUND
      - name: WAREHOUSE1
        search-location-group-names: RACK1,RACK2
        type: REPLENISHMENT

---
spring:
  profiles: TEST

owms:
  movement:
    targets:
      - name: ERR_/0001/0000/0000/0000
        search-location-group-names: RACK1,RACK2
        type: INBOUND
